name: QAbrakai workflow - Onboarding challenge

on:
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Print message
    - name: Print message
      run: echo "Hello GA!"   
