name: Workflow2

on: 
  repository_dispatch:
    types: [slack-notify]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running
        run: |
          echo "Running workflow 2"