name: Workflow1

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo test
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_GA_TEST }}
          repository: eavendano01/ga-newman-schedule-test
          event-type: slack-notify
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'